version: '3'

volumes:
  db:
  redis:
  rabbitmq:

networks:
  laravel.test:
      driver: bridge

services:
  nginx:
    build:
      context: ./.docker
      dockerfile: nginx.dockerfile
    ports:
      - ${HTTP_PORT:-85}:85
      - ${HTTPS_PORT:-4469}:4469
    volumes:
      - ./:/var/www
      - ./.docker/nginx/:/etc/nginx/conf.d/
    depends_on:
      - app
#      - redis
      - mysql
#      - mailhog
#     - rabbitmq
    networks:
      - laravel.test

  app:
      build:
          context: ./.docker
          dockerfile: app.dockerfile
      ports:
          - ${APP_PHP_FPM_PORT:-9005}:9005
      volumes:
          - ./.docker/app/php.ini:/usr/local/etc/php/php.ini
          - ./:/var/www
          - ./.docker/supervisord.conf:/etc/supervisor/conf.d/supervisord.conf # для онлайн редактирования конфига супервизора
          - ./storage/logs/supervisor:/var/log/supervisor # для логов супервизора
      environment:
          XDEBUG_CONFIG: client_host=${XDEBUG_REMOTE_HOST} client_port=${XDEBUG_STORM_PORT} remote_enable=1
          PHP_IDE_CONFIG: serverName=${XDEBUG_STORM_SERVER_NAME}
#      depends_on:
#          - rabbitmq
      networks:
          - laravel.test

  mysql:
    image: mariadb:10.6
    tty: true
    command: ['mysqld', '--bind-address=0.0.0.0', '--port=3309']
    ports:
        - ${MYSQL_PORT:-3309}:3309
    environment:
      MYSQL_DATABASE: crassh
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    volumes:
      - db:/var/lib/mysql
    networks:
      - laravel.test



#  redis:
#    image: redis:alpine
#    ports:
#      - ${REDIS_PORT:-6379}:6379
#    volumes:
#      - redis:/data
#    networks:
#      - laravel.test

#  rabbitmq:
#    image: rabbitmq:3.13.2
#    environment:
#      RABBITMQ_DEFAULT_USER: guest
#      RABBITMQ_DEFAULT_PASS: guest
#      RABBITMQ_DEFAULT_VHOST: /
#    ports:
#      - ${RABBITMQ_PORT:-5672}:5672
#      - ${RABBITMQ_PORT_CP:-15672}:15672
#    volumes:
#      - rabbitmq:/var/lib/rabbitmq
#      - ./storage/logs/rabbitmq:/var/log/rabbitmq # для логов реббита. Но по дефолту их нет, пишутся в консоль.
#    networks:
#      - laravel.test

#  mailhog:
#    image: mailhog/mailhog:latest
#    ports:
#      - ${MAILHOG_PORT:-1025}:1025
#      - ${MAILHOG_PANEL_POR:-8025}:8025
#    networks:
#      - laravel.test

